### ISSUE TITLE
csv.Sniffer.has_header isnt reliable

### ISSUE THREAD

**Issue by feiloo** [cio-abcd/variantinterpretation#11]
### Description of the bug

the samplesheet.csv files contain only paths. 
pythons cs.Sniffer.has_header can fail because its only a heuristic.
this causes the pipeline to fail if there are no numeric looking values in the csv.
it happened during my testing

see [this line](https://github.com/cio-abcd/variantinterpretation/blob/6438b14644e86d588a71ce9c05e4a0458feb4f0e/bin/check_samplesheet.py#L161)
and [python csv module documentation](https://docs.python.org/3.11/library/csv.html#csv.Sniffer)

we can probably just replace/remove the check

**Comment by biolancer** [comment]
Yes, sounds reasonable. Commenting out the lines 112 to 134 of check_samplesheet.py and changing 

`reader = csv.DictReader(in_handle, dialect=sniff_format(in_handle))`
to

`reader = csv.DictReader(in_handle)`

fixes the problem. It's a rather dirty bugfix by removing the function, we should consider defining the header columns to check for as soon as we have a more complete samplesheet.
