### ISSUE TITLE
Report visualization

### ISSUE THREAD

**Issue by biolancer** [cio-abcd/variantinterpretation#6]
### Description of feature

The output of the variant interpretation module should be summarized using a GUI or HTML report file, which can be browsed without the use of the CLI. In a first iteration, generation of an interactive HTML report should be focused until a suitable GUI application is found and could be integrated.

The HTML report file should include all annotated variants and relevant log data on the pre- and postprocessing procedures used for data generation as core output. Potential features of the HTML report are up for discussion.

HTML feature propositions:
- Filterable report files (f.e. based on ClinVar significance, reported allele frequency, etc...)
- Generation of "diagnostical report-ready text blocks" for quick export

Proposed HTML report/GUI applications:
- PCGR (https://github.com/sigven/pcgr, generates HTML reports)
- Visualization software in development mentioned by KH

**Comment by sci-kai** [comment]
In our last meeting we decided to use [datavzrd](https://github.com/datavzrd/datavzrd) von Johannes Köster as HTML report tool.
meets the requirements and produces standalone, compact and easily configurable report.
